COLUMN_METADATA = {
    "customers": {
        "customer_id": {"description": "Unique identifier for each customer"},
        "name": {"description": "Full name of the customer"},
        "email": {"description": "Email address of the customer"},
        "city": {"description": "City where the customer resides"},
        "state": {"description": "State where the customer resides"},
        "country": {"description": "Country where the customer resides"},
        "signup_date": {"description": "Date when the customer signed up"},
        "customer_segment": {"description": "Segment classification of customer (e.g. VIP, Regular)"},
    },
    "products": {
        "product_id": {"description": "Unique identifier for each product"},
        "product_name": {"description": "Name of the product"},
        "category": {"description": "Category of the product"},
        "subcategory": {"description": "Subcategory of the product"},
        "price": {"description": "Selling price of the product"},
        "cost": {"description": "Cost price of the product"},
    },
    "orders": {
        "order_id": {"description": "Unique identifier for each order"},
        "customer_id": {"description": "ID of the customer who placed the order"},
        "order_date": {"description": "Date and time when the order was placed"},
        "status": {"description": "Current status of the order (e.g. Delivered, Pending, Cancelled)"},
        "region": {"description": "Geographic region of the order"},
    },
    "order_items": {
        "order_item_id": {"description": "Unique identifier for each order item line"},
        "order_id": {"description": "ID of the order"},
        "product_id": {"description": "ID of the product ordered"},
        "quantity": {"description": "Quantity of the product ordered"},
        "unit_price": {"description": "Price per unit at time of purchase"},
        "discount": {"description": "Discount applied as a decimal (0.0 to 1.0)"},
    },
    "payments": {
        "payment_id": {"description": "Unique identifier for each payment"},
        "order_id": {"description": "ID of the order paid for"},
        "payment_date": {"description": "Date and time of payment"},
        "payment_method": {"description": "Method used for payment (e.g. Credit Card, PayPal)"},
        "amount": {"description": "Amount paid"},
        "payment_status": {"description": "Status of payment transaction"},
    },
    "reviews": {
        "review_id": {"description": "Unique identifier for each review"},
        "customer_id": {"description": "ID of the customer writing the review"},
        "product_id": {"description": "ID of the product being reviewed"},
        "rating": {"description": "Product rating score from 1 to 5 stars"},
        "review_text": {"description": "Text content of customer review"},
        "review_date": {"description": "Date review was submitted"},
    },
}

# METRIC_METADATA = {
#     "Total Revenue": {
#         "description": "Total sales revenue generated from order items taking discount into account",
#         "formula": "SUM(quantity * unit_price * (1 - discount))",
#         "tables": ["order_items"],
#     },
#     "Total Profit": {
#         "description": "Total profit generated after subtracting cost from revenue",
#         "formula": "SUM(quantity * (unit_price * (1 - discount) - cost))",
#         "tables": ["order_items", "products"],
#     },
#     "Average Order Value (AOV)": {
#         "description": "Average revenue per order",
#         "formula": "Total Revenue / COUNT(DISTINCT order_id)",
#         "tables": ["orders", "order_items"],
#     },
#     "Customer Lifetime Value (CLV)": {
#         "description": "Total revenue generated by a customer across all their orders",
#         "formula": "SUM(quantity * unit_price * (1 - discount)) grouped by customer_id",
#         "tables": ["customers", "orders", "order_items"],
#     },
# }


METRIC_METADATA = {
    "revenue": {
        "description": (
            "Total sales value after applying the discount."
        ),
        "formula": (
            "SUM(quantity * unit_price * (1 - discount))"
        ),
        "formula_type": "sql_expression",
        "tables": [
            "order_items"
        ],
        "required_columns": [
            "quantity",
            "unit_price",
            "discount"
        ],
        "keywords": [
            "revenue",
            "sales",
            "sales value",
            "total sales"
        ]
    },
    "quantity": {
    "description": "Total number of units purchased.",
    "formula": "SUM(quantity)",
    "formula_type": "sql_expression",
    "tables": ["order_items"],
    "required_columns": ["quantity"],
    "keywords": [
        "quantity",
        "units",
        "units sold",
        "number of units"
    ]
}
}