from evaluation.answer_evaluator import AnswerCorrectnessEvaluator
from evaluation.dataset import load_evaluation_dataset


def _case(case_id):
    dataset = load_evaluation_dataset()
    return next(case for case in dataset.cases if case.case_id == case_id)


def test_revenue_answer_is_semantically_correct():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("revenue-001"),
        "The total revenue is calculated after applying discounts.",
    )

    assert result.match is True
    assert result.missing_concepts == []


def test_top_five_answer_requires_count_and_descending_order():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("topn-001"),
        "Here are the five products ranked from highest to lowest revenue.",
    )

    assert result.match is True
    assert result.concept_coverage == 1.0


def test_top_five_answer_fails_when_count_is_wrong():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("topn-001"),
        "The products are ranked from highest to lowest revenue.",
    )

    assert result.match is False
    assert "five" in result.missing_concepts


def test_delivered_revenue_answer_requires_delivered_filter():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("filter-001"),
        "Revenue generated by delivered orders only.",
    )

    assert result.match is True
    assert result.result_contract_checks["delivered_filter"] is True


def test_year_filter_is_checked_from_answer_contract():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("time-001"),
        "The revenue for orders placed in calendar year 2025 is shown below.",
    )

    assert result.match is True
    assert result.result_contract_checks["year_2025"] is True


def test_case_without_expected_answer_is_not_evaluated():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(
        _case("unsupported-001"),
        "I cannot answer that request.",
    )

    assert result.evaluated is False
    assert result.match is False


def test_empty_answer_fails_evaluation():
    evaluator = AnswerCorrectnessEvaluator()
    result = evaluator.evaluate_case(_case("quantity-001"), "")

    assert result.evaluated is True
    assert result.match is False
    assert "Generated answer is empty." in result.errors


def test_summary_excludes_unevaluated_cases():
    evaluator = AnswerCorrectnessEvaluator()
    results = [
        evaluator.evaluate_case(
            _case("revenue-001"),
            "Total revenue after applying discounts.",
        ),
        evaluator.evaluate_case(
            _case("unsupported-001"),
            "I cannot answer that request.",
        ),
    ]

    summary = evaluator.summarize(results)

    assert summary.evaluated_cases == 1
    assert summary.matched_cases == 1
    assert summary.accuracy == 1.0
